# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget arch tf gf js trace work plug vt ar kind sdf ndr sdr pcp usd usdGeom usdVol usdLux usdShade usdRender usdHydra usdRi usdSkel usdUI usdUtils)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target arch
add_library(arch STATIC IMPORTED)

set_target_properties(arch PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Ws2_32.lib;Dbghelp.lib"
)

# Create imported target tf
add_library(tf STATIC IMPORTED)

set_target_properties(tf PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;E:/db16/build/S/VS1564R/Release/tbb/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch;Shlwapi.lib;E:/db16/build/S/VS1564R/Release/tbb/lib/tbb_static.lib"
)

# Create imported target gf
add_library(gf STATIC IMPORTED)

set_target_properties(gf PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target js
add_library(js STATIC IMPORTED)

set_target_properties(js PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target trace
add_library(trace STATIC IMPORTED)

set_target_properties(trace PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;E:/db16/build/S/VS1564R/Release/tbb/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch;E:/db16/build/S/VS1564R/Release/tbb/lib/tbb_static.lib"
)

# Create imported target work
add_library(work STATIC IMPORTED)

set_target_properties(work PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/tbb/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch;E:/db16/build/S/VS1564R/Release/tbb/lib/tbb_static.lib"
)

# Create imported target plug
add_library(plug STATIC IMPORTED)

set_target_properties(plug PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;E:/db16/build/S/VS1564R/Release/tbb/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch;E:/db16/build/S/VS1564R/Release/tbb/lib/tbb_static.lib"
)

# Create imported target vt
add_library(vt STATIC IMPORTED)

set_target_properties(vt PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;E:/db16/build/S/VS1564R/Release/tbb/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch;E:/db16/build/S/VS1564R/Release/tbb/lib/tbb_static.lib"
)

# Create imported target ar
add_library(ar STATIC IMPORTED)

set_target_properties(ar PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target kind
add_library(kind STATIC IMPORTED)

set_target_properties(kind PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target sdf
add_library(sdf STATIC IMPORTED)

set_target_properties(sdf PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target ndr
add_library(ndr STATIC IMPORTED)

set_target_properties(ndr PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target sdr
add_library(sdr STATIC IMPORTED)

set_target_properties(sdr PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:ndr>;ndr;-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target pcp
add_library(pcp STATIC IMPORTED)

set_target_properties(pcp PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;E:/db16/build/S/VS1564R/Release/tbb/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch;E:/db16/build/S/VS1564R/Release/tbb/lib/tbb_static.lib"
)

# Create imported target usd
add_library(usd STATIC IMPORTED)

set_target_properties(usd PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;E:/db16/build/S/VS1564R/Release/tbb/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:pcp>;pcp;-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:kind>;kind;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch;E:/db16/build/S/VS1564R/Release/tbb/lib/tbb_static.lib"
)

# Create imported target usdGeom
add_library(usdGeom STATIC IMPORTED)

set_target_properties(usdGeom PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;E:/db16/build/S/VS1564R/Release/tbb/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:usd>;usd;-WHOLEARCHIVE:\$<TARGET_FILE:pcp>;pcp;-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:kind>;kind;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch;E:/db16/build/S/VS1564R/Release/tbb/lib/tbb_static.lib"
)

# Create imported target usdVol
add_library(usdVol STATIC IMPORTED)

set_target_properties(usdVol PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:usdGeom>;usdGeom;-WHOLEARCHIVE:\$<TARGET_FILE:usd>;usd;-WHOLEARCHIVE:\$<TARGET_FILE:pcp>;pcp;-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:kind>;kind;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target usdLux
add_library(usdLux STATIC IMPORTED)

set_target_properties(usdLux PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:usdGeom>;usdGeom;-WHOLEARCHIVE:\$<TARGET_FILE:usd>;usd;-WHOLEARCHIVE:\$<TARGET_FILE:pcp>;pcp;-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:kind>;kind;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target usdShade
add_library(usdShade STATIC IMPORTED)

set_target_properties(usdShade PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:usdGeom>;usdGeom;-WHOLEARCHIVE:\$<TARGET_FILE:usd>;usd;-WHOLEARCHIVE:\$<TARGET_FILE:pcp>;pcp;-WHOLEARCHIVE:\$<TARGET_FILE:sdr>;sdr;-WHOLEARCHIVE:\$<TARGET_FILE:ndr>;ndr;-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:kind>;kind;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target usdRender
add_library(usdRender STATIC IMPORTED)

set_target_properties(usdRender PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:usdGeom>;usdGeom;-WHOLEARCHIVE:\$<TARGET_FILE:usd>;usd;-WHOLEARCHIVE:\$<TARGET_FILE:pcp>;pcp;-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:kind>;kind;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target usdHydra
add_library(usdHydra STATIC IMPORTED)

set_target_properties(usdHydra PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:usdShade>;usdShade;-WHOLEARCHIVE:\$<TARGET_FILE:usdGeom>;usdGeom;-WHOLEARCHIVE:\$<TARGET_FILE:usd>;usd;-WHOLEARCHIVE:\$<TARGET_FILE:pcp>;pcp;-WHOLEARCHIVE:\$<TARGET_FILE:sdr>;sdr;-WHOLEARCHIVE:\$<TARGET_FILE:ndr>;ndr;-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:kind>;kind;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target usdRi
add_library(usdRi STATIC IMPORTED)

set_target_properties(usdRi PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:usdShade>;usdShade;-WHOLEARCHIVE:\$<TARGET_FILE:usdLux>;usdLux;-WHOLEARCHIVE:\$<TARGET_FILE:usdGeom>;usdGeom;-WHOLEARCHIVE:\$<TARGET_FILE:usd>;usd;-WHOLEARCHIVE:\$<TARGET_FILE:pcp>;pcp;-WHOLEARCHIVE:\$<TARGET_FILE:sdr>;sdr;-WHOLEARCHIVE:\$<TARGET_FILE:ndr>;ndr;-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:kind>;kind;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target usdSkel
add_library(usdSkel STATIC IMPORTED)

set_target_properties(usdSkel PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;E:/db16/build/S/VS1564R/Release/tbb/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:usdGeom>;usdGeom;-WHOLEARCHIVE:\$<TARGET_FILE:usd>;usd;-WHOLEARCHIVE:\$<TARGET_FILE:pcp>;pcp;-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:kind>;kind;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch;E:/db16/build/S/VS1564R/Release/tbb/lib/tbb_static.lib"
)

# Create imported target usdUI
add_library(usdUI STATIC IMPORTED)

set_target_properties(usdUI PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:usd>;usd;-WHOLEARCHIVE:\$<TARGET_FILE:pcp>;pcp;-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:kind>;kind;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

# Create imported target usdUtils
add_library(usdUtils STATIC IMPORTED)

set_target_properties(usdUtils PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PXR_PYTHON_ENABLED=1;PXR_STATIC=1"
  INTERFACE_INCLUDE_DIRECTORIES "E:/db16/build/S/VS1564R/Release/boost/include/boost-1_68;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-WHOLEARCHIVE:\$<TARGET_FILE:usdGeom>;usdGeom;-WHOLEARCHIVE:\$<TARGET_FILE:usd>;usd;-WHOLEARCHIVE:\$<TARGET_FILE:pcp>;pcp;-WHOLEARCHIVE:\$<TARGET_FILE:sdf>;sdf;-WHOLEARCHIVE:\$<TARGET_FILE:kind>;kind;-WHOLEARCHIVE:\$<TARGET_FILE:ar>;ar;-WHOLEARCHIVE:\$<TARGET_FILE:vt>;vt;-WHOLEARCHIVE:\$<TARGET_FILE:plug>;plug;-WHOLEARCHIVE:\$<TARGET_FILE:work>;work;-WHOLEARCHIVE:\$<TARGET_FILE:trace>;trace;-WHOLEARCHIVE:\$<TARGET_FILE:js>;js;-WHOLEARCHIVE:\$<TARGET_FILE:gf>;gf;-WHOLEARCHIVE:\$<TARGET_FILE:tf>;tf;-WHOLEARCHIVE:\$<TARGET_FILE:arch>;arch"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/pxrTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
